# Generated by Django 4.1.3 on 2022-12-28 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelclass',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
